"""add cascade deletes

Revision ID: 3d6dce833603
Revises: a72c6c5c7edd
Create Date: 2025-11-18 15:17:49.282636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '3d6dce833603'
down_revision: Union[str, Sequence[str], None] = 'a72c6c5c7edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chats_workflow_id_fkey'), 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('messages_chat_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('workflowedges_workflow_id_fkey'), 'workflowedges', type_='foreignkey')
    op.create_foreign_key(None, 'workflowedges', 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('workflownodes_workflow_id_fkey'), 'workflownodes', type_='foreignkey')
    op.create_foreign_key(None, 'workflownodes', 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflownodes', type_='foreignkey')
    op.create_foreign_key(op.f('workflownodes_workflow_id_fkey'), 'workflownodes', 'workflows', ['workflow_id'], ['id'])
    op.drop_constraint(None, 'workflowedges', type_='foreignkey')
    op.create_foreign_key(op.f('workflowedges_workflow_id_fkey'), 'workflowedges', 'workflows', ['workflow_id'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_chat_id_fkey'), 'messages', 'chats', ['chat_id'], ['id'])
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key(op.f('chats_workflow_id_fkey'), 'chats', 'workflows', ['workflow_id'], ['id'])
    # ### end Alembic commands ###
